spring:
  datasource:
    url: jdbc:mysql://${CLEARDB_DATABASE_URL}/${DB_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true